//Source: https://github.com/SebLague/Boids/blob/master/Assets/Scripts/BoidCompute.compute﻿

#pragma kernel CSMain
static const int threadGroupSize = 1024;

//Structure should mirror BoidData in "Boid.cs"
struct Particle {
    float3 position;
    float3 direction;
    float speed;

    float3 flockHeading;
    float3 flockCentre;
    float3 separationForce;
    int numFlockmates;
    float totalWeight;
};

RWStructuredBuffer<Particle> particles;
int numParticles;
float pressureRadius;
float separationRadius;
float minSeparationRadius;
float fov;

[numthreads(threadGroupSize,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    for (int indexB = 0; indexB < numParticles; indexB ++) {
        if (id.x != (uint)indexB) {
            Particle particleB = particles[indexB];
            
        }
    }
    
}